return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 25,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 71,
  properties = {},
  tilesets = {
    {
      name = "castle1F",
      firstgid = 1,
      filename = "../tilesets/castle1F.tsx"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 25,
      height = 12,
      id = 1,
      name = "tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 88, 89, 89, 89, 89, 89, 90, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 2, 75, 76, 77, 78, 79, 6, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 88, 89, 89, 89, 89, 89, 89, 90, 54, 91, 92, 93, 94, 95, 54, 88, 89, 89, 89, 89, 89, 89, 89, 55,
        55, 54, 12, 13, 14, 15, 16, 54, 18, 3, 107, 108, 109, 110, 111, 5, 2, 7, 8, 9, 10, 11, 54, 54, 55,
        55, 54, 28, 29, 30, 31, 32, 4, 5, 35, 123, 124, 125, 126, 127, 37, 3, 23, 24, 25, 26, 27, 54, 54, 55,
        55, 54, 54, 45, 46, 47, 38, 39, 18, 70, 73, 73, 73, 73, 73, 71, 2, 54, 40, 41, 42, 54, 4, 54, 55,
        55, 20, 20, 61, 62, 58, 20, 36, 21, 84, 84, 84, 84, 84, 84, 84, 19, 20, 56, 57, 58, 20, 20, 20, 55,
        55, 73, 73, 86, 84, 87, 73, 73, 74, 84, 84, 84, 84, 84, 84, 84, 72, 73, 86, 84, 87, 73, 73, 73, 55,
        55, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 55,
        55, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 84, 84, 84, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 440,
          width = 400,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 440,
          width = 400,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 280,
          width = 320,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 320,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 280,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 240,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 280,
          width = 106.667,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 480,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 280,
          width = 106.667,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 53,
          name = "spawn",
          type = "",
          shape = "point",
          x = 496.296,
          y = 449.911,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "respawn",
          type = "",
          shape = "point",
          x = 500,
          y = 380,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "exit",
          type = "",
          shape = "point",
          x = 179.333,
          y = 356.667,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "disengage",
          type = "",
          shape = "point",
          x = 600,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 255, 0 },
      properties = {},
      objects = {
        {
          id = 55,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 280,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "* Kris and susie's rooms!",
            ["text2"] = "* And queen's! and lancers!",
            ["text3"] = "* and mine too i guess"
          }
        },
        {
          id = 56,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 200,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* It doesn't open. It's closed by some contraption."
          }
        },
        {
          id = 49,
          name = "savepoint",
          type = "",
          shape = "point",
          x = 500,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["marker"] = "respawn",
            ["simple"] = true,
            ["text"] = "* Something feels...[wait:5] wrong."
          }
        },
        {
          id = 62,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 147,
          y = 266.667,
          width = 73,
          height = 39.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "castle2",
            ["marker"] = "spawn"
          }
        },
        {
          id = 65,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 723.667,
          y = 326,
          width = 50.6667,
          height = 107,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "examples.dummy",
            ["once"] = false
          }
        },
        {
          id = 70,
          name = "enemy",
          type = "",
          shape = "point",
          x = 660,
          y = 380,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "dummy",
            ["encounter"] = "dummy"
          }
        }
      }
    }
  }
}
